version: 0.2
env:
  exported-variables:
    - APP_NAME
    - APP_VERSION
    - APP_ENVIRONMENT
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - npm install -g jfrog-cli-go --unsafe-perm=true
  pre_build:
    commands:
      - jfrog c add artifactory --user=$JFROG_TALENTPORT_RESOLVE_USER --password=$JFROG_TALENTPORT_RESOLVE_PASS --url=$JFROG_URL --interactive=false
      - jfrog rt mvnc --server-id-resolve=artifactory --server-id-deploy=artifactory --repo-resolve-releases=$JFROG_TALENTPORT_RESOLVE_REPO_MAVEN --repo-resolve-snapshots=$JFROG_TALENTPORT_RESOLVE_REPO_MAVEN_SNAPSHOT --repo-deploy-releases=$JFROG_TALENTPORT_DEPLOY_REPO_MAVEN --repo-deploy-snapshots=$JFROG_TALENTPORT_DEPLOY_REPO_MAVEN_SNAPSHOT 
      - aws s3 cp s3://$BUCKET_NAME/config/template.json ./template.json
  build:
    commands:
      - jfrog rt mvn package -Dartifactory.publish.artifacts=false
      - APP_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
      - APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
      - ARTIFACT_NAME=$APP_NAME-$APP_VERSION.jar
      - unzip -q dist/$ARTIFACT_NAME -d dist
      - rm -fr dist/$ARTIFACT_NAME
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET_NAME --output-template-file outputtemplate.yml --kms-key-id $KMS_KEY_ID --s3-prefix $APP_NAME/Artifacts
artifacts:
  files:
    - template.yml
    - outputtemplate.yml
    - template.json